### ISSUE TITLE
개인 작업 페이지 만들기

### ISSUE THREAD

**Issue by suri0000** [suri0000/sweetSwift#1]
## 작업 목적 ⚒️
- 메인뷰를 만듭니다.

## To-do 📝
- [x] 자판기 위에 버튼 올리기
- [ ] 버튼에서 개인 페이지로 네비게이션
- [ ] 개인 페이지 만들기
